contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #viralverify channel"
    url: https://nfcore.slack.com/channels/viralverify
    about: Discussion about the nf-core/viralverify pipeline
